### ISSUE TITLE
How to get "shortest path" between two positions and corresponding actions ?

### ISSUE THREAD

**Issue by Sunnyzhr** [facebookresearch/splitnet#13]
The splitnet is a fantastic network, and I am doing my graduate project on it. However, I encounter problem when getting shortest path between two positions. Here are my attempts:
## Attempt1
I notice that [self.habitat_env.get_metrics()](https://github.com/facebookresearch/splitnet/blob/197ad405c1387bfde16abaf4705b7e0dab628f4f/reinforcement_learning/nav_rl_env.py#L47) could get the "spl" information. Thus, it might help show how to get the "shortest path". But, I couldn't find where this function is defined.

## Attempt2
I try to use [habitat_sim.nav.ShortestPath](https://aihabitat.org/docs/habitat-sim/habitat_sim.nav.ShortestPath.html). But I failed, and it's said that this class is no longer implemented.

## Attempt3 
I try to use [habitat_sim.nav.GreedyGeodesicFollower](https://aihabitat.org/docs/habitat-sim/habitat_sim.nav.GreedyGeodesicFollower.html). However, I encounter trouble when initializing. Here is my code:
```
from train_splitnet import HabitatRLTrainAndEvalRunner
from habitat_sim.nav.greedy_geodesic_follower import GreedyGeodesicFollower
from habitat_sim.nav.greedy_geodesic_follower import PathFinder
class Follow(HabitatRLTrainAndEvalRunner):
    def __init__(self, create_decoder=True):
        super(Follow, self).__init__(create_decoder)

if __name__ == "__main__":
    runner = Follow()
    PF = PathFinder()
    GF = GreedyGeodesicFollower(PF,runner.agent)
```
**'VisualPolicy' object has no attribute 'agent_config'**. Here is the error message:

> Traceback (most recent call last):
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/u/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
>     cli.main()
>   File "/home/u/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
>     run()
>   File "/home/u/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
>     runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/u/Desktop/splitnet/hello_world.py", line 11, in <module>
>     GF = GreedyGeodesicFollower(PF,runner.agent)
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/nav/greedy_geodesic_follower.py", line 86, in __init__
>     key, spec = self._find_action("move_forward")
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/nav/greedy_geodesic_follower.py", line 124, in _find_action
>     self.agent.agent_config.action_space.items(),
>   File "/home/u/anaconda3/envs/habitat-yolo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
>     type(self).__name__, name))
> torch.nn.modules.module.ModuleAttributeError: 'VisualPolicy' object has no attribute 'agent_config'

**Comment by StOnEGiggity** [comment]
Hi, @Sunnyzhr. It seems that you are using the new version of habitat-lab or habitat-sim. It is not compatible with SplitNet. Actually, SplitNet is a navigation project, which utilizes the same "shortest path" algorithm as habitat-lab.
I recommend you can report related issues under the repo (https://github.com/facebookresearch/habitat-lab).

**Comment by danielgordon10** [comment]
If you get it to work with the new habitat, please submit a pull request here. I'm sure it would be appreciated.
